class MovableObject extends DrawableObject {
  x;
  y;
  img;
  mirrorX = false;
  imageCache = {};
  currentImage = 0;

  /**
   *
   * @param {Array} images names of the frames to animate
   * @param {Number} speed obligatory speed of the animation in ms@
   *
   * animates the individual sprite as needed
   */
  animate(images, speed = 100) {
    setInterval(() => {
      let i = this.currentImage % images.length;
      let path = images[i];
      this.img = this.imageCache[path];
      this.currentImage++;
    }, speed);
  }

  /**
   *
   * @param {String} path name of the path
   *
   * transforms the string into usable path
   */
  loadImage(path) {
    this.img = new Image();
    this.img.src = path;
  }

  /**
   *
   * @param {string[]} arr Image paths, e.g. generated by createAnimationImages().
   */
  loadImages(arr) {
    arr.forEach((path) => {
      const img = new Image();
      img.src = path;
      this.imageCache[path] = img;
    });
  }

  moveRight(speed = 0.32) {
    this.x += speed;
  }
  moveLeft(speed = 0.32) {
    this.x -= speed;
  }

  jump() {
    console.log("Jumping");
    this.y -= 10; // Move the character up by 10 pixels
  }
}
