class MovableObject extends DrawableObject {
  x;
  y;
  img;
  mirrorX = false;
  direction = 1;
  imageCache = {};
  currentImage = 0;
  currentAnimation;
  speed = 0.32; // default speed
  animationInterval;
  walkingSound;
  speedY = 0;
  acceleration = 0.8;
  leftOffset;
  rightOffset;
  topOffset = 0;
  bottomOffset = 0;

  /**
   *
   * @param {Array} images names of the frames to animate
   * @param {Number} speed obligatory speed of the animation in ms@
   *
   * animates the individual sprite as needed
   */
  animate(images, speed = 100) {
    this.animationInterval = setInterval(() => {
      let i = this.currentImage % images.length;
      let path = images[i];
      this.img = this.imageCache[path];
      this.currentImage++;
    }, speed);
  }

  /**
   * clear the indiviual animation-interval
   */
  stopAnimation() {
    clearInterval(this.animationInterval);
  }

  /**
   *
   * @param {Array} images frames to animate
   * @param {Number} speed obligatory speed of the animation in ms@
   *
   * animates the individual sprite as needed and stops after one cycle
   */
  animateOnce(images, speed = 400) {
    this.stopAnimation();
    this.currentImage = 0;

    this.animationInterval = setInterval(() => {
      let path = images[this.currentImage];
      this.img = this.imageCache[path];
      this.currentImage++;

      if (this.currentImage >= images.length) {
        this.stopAnimation();
      }
    }, speed);
  }

  /**
   *
   * @param {String} path name of the path
   *
   * transforms the string into usable path
   */
  loadImage(path) {
    this.img = new Image();
    this.img.src = path;
  }

  /**
   *
   * @param {string[]} arr Image paths, e.g. generated by createAnimationImages().
   */
  loadImages(arr) {
    arr.forEach((path) => {
      const img = new Image();
      img.src = path;
      this.imageCache[path] = img;
    });
  }

  move(speed) {
    this.x += speed * this.direction;
  }

  jump() {
    console.log("Jumping");
    this.y -= 10; // Move the character up by 10 pixels
  }

  /**
   * affects all moving objects that change y
   */
  applyGravity() {
    this.y += this.speedY;
    this.speedY += this.acceleration;
  }

  setAnimation(images, speed) {
    if (this.currentAnimation === images) return;

    this.stopAnimation();
    this.animate(images, speed);
    this.currentAnimation = images;
  }

  isColliding(mo) {
    const thisOffsets = this.getCollisionOffsets();
    const moOffsets = mo.getCollisionOffsets();

    const thisLeft = this.x + thisOffsets.left;
    const thisRight = this.x + this.width - thisOffsets.right;
    const thisTop = this.y + thisOffsets.top;
    const thisBottom = this.y + this.height - thisOffsets.bottom;

    const moLeft = mo.x + moOffsets.left;
    const moRight = mo.x + mo.width - moOffsets.right;
    const moTop = mo.y + moOffsets.top;
    const moBottom = mo.y + mo.height - moOffsets.bottom;

    return (
      thisRight > moLeft &&
      thisLeft < moRight &&
      thisBottom > moTop &&
      thisTop < moBottom
    );
  }

  checkCollisions() {
    this.world.level.enemies.forEach((enemy) => {
      if (this.isColliding(enemy)) {
        console.log("collision");
      }
    });
  }

  getCollisionOffsets() {
    return {
      left: this.mirrorX ? this.leftOffset : this.rightOffset,
      right: this.mirrorX ? this.rightOffset : this.leftOffset,
      top: this.topOffset,
      bottom: this.bottomOffset,
    };
  }

  isInTheAir() {
    return this.y < this.groundY;
  }

  shouldMirror() {
    return this.direction === 1;
  }
}
