class MovableObject extends DrawableObject {
  x;
  y;
  img;
  mirrorX = false;
  imageCache = {};
  currentImage = 0;
  currentAnimation;
  speed = 0.32; // default speed
  animationInterval;
  walkingSound;
  speedY = 0;
  acceleration = 0.8;
  leftOffset;
  rightOffset;

  /**
   *
   * @param {Array} images names of the frames to animate
   * @param {Number} speed obligatory speed of the animation in ms@
   *
   * animates the individual sprite as needed
   */
  animate(images, speed = 100) {
    this.animationInterval = setInterval(() => {
      let i = this.currentImage % images.length;
      let path = images[i];
      this.img = this.imageCache[path];
      this.currentImage++;
    }, speed);
  }

  /**
   * clear the indiviual animation-interval
   */
  stopAnimation() {
    clearInterval(this.animationInterval);
  }

  /**
   *
   * @param {Array} images frames to animate
   * @param {Number} speed obligatory speed of the animation in ms@
   *
   * animates the individual sprite as needed and stops after one cycle
   */
  animateOnce(images, speed = 400) {
    this.stopAnimation();
    this.currentImage = 0;

    this.animationInterval = setInterval(() => {
      let path = images[this.currentImage];
      this.img = this.imageCache[path];
      this.currentImage++;

      if (this.currentImage >= images.length) {
        this.stopAnimation();
      }
    }, speed);
  }

  /**
   *
   * @param {String} path name of the path
   *
   * transforms the string into usable path
   */
  loadImage(path) {
    this.img = new Image();
    this.img.src = path;
  }

  /**
   *
   * @param {string[]} arr Image paths, e.g. generated by createAnimationImages().
   */
  loadImages(arr) {
    arr.forEach((path) => {
      const img = new Image();
      img.src = path;
      this.imageCache[path] = img;
    });
  }

  moveRight(speed = 0.32) {
    this.x += speed;
  }
  moveLeft(speed = 0.32) {
    this.x -= speed;
  }

  jump() {
    console.log("Jumping");
    this.y -= 10; // Move the character up by 10 pixels
  }

  /**
   * affects all moving objects that change y
   */
  applyGravity() {
    this.y += this.speedY;
    this.speedY += this.acceleration;
  }

  setAnimation(images, speed) {
    if (this.currentAnimation === images) return;

    this.stopAnimation();
    this.animate(images, speed);
    this.currentAnimation = images;
  }
}
